// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: essence.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace NydusNetwork.API.Protocol {

  /// <summary>Holder for reflection information generated from essence.proto</summary>
  public static partial class EssenceReflection {

    #region Descriptor
    /// <summary>File descriptor for essence.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EssenceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1lc3NlbmNlLnByb3RvEhlOeWR1c05ldHdvcmsuQVBJLlByb3RvY29sGgpk",
            "YXRhLnByb3RvIvMECgdFc3NlbmNlEhMKC0RhdGFWZXJzaW9uGAEgASgJEhEK",
            "CURhdGFCdWlsZBgCIAEoBRI5CglhYmlsaXRpZXMYAyADKAsyJi5OeWR1c05l",
            "dHdvcmsuQVBJLlByb3RvY29sLkFiaWxpdHlEYXRhEjIKBWJ1ZmZzGAQgAygL",
            "MiMuTnlkdXNOZXR3b3JrLkFQSS5Qcm90b2NvbC5CdWZmRGF0YRI6Cgl1bml0",
            "VHlwZXMYBSADKAsyJy5OeWR1c05ldHdvcmsuQVBJLlByb3RvY29sLlVuaXRU",
            "eXBlRGF0YRI4Cgh1cGdyYWRlcxgGIAMoCzImLk55ZHVzTmV0d29yay5BUEku",
            "UHJvdG9jb2wuVXBncmFkZURhdGESQAoNdW5pdFByb2R1Y2VycxgHIAMoCzIp",
            "Lk55ZHVzTmV0d29yay5BUEkuUHJvdG9jb2wuTXVsdGlWYWx1ZVBhaXISSAoV",
            "dW5pdFJlcXVpcmVkQnVpbGRpbmdzGAggAygLMikuTnlkdXNOZXR3b3JrLkFQ",
            "SS5Qcm90b2NvbC5NdWx0aVZhbHVlUGFpchI+ChByZXNlYXJjaFByb2R1Y2Vy",
            "GAkgAygLMiQuTnlkdXNOZXR3b3JrLkFQSS5Qcm90b2NvbC5WYWx1ZVBhaXIS",
            "RwoZcmVzZWFyY2hSZXF1aXJlZEJ1aWxkaW5ncxgKIAMoCzIkLk55ZHVzTmV0",
            "d29yay5BUEkuUHJvdG9jb2wuVmFsdWVQYWlyEkYKGHJlc2VhcmNoUmVxdWly",
            "ZWRSZXNlYXJjaBgLIAMoCzIkLk55ZHVzTmV0d29yay5BUEkuUHJvdG9jb2wu",
            "VmFsdWVQYWlyIicKCVZhbHVlUGFpchILCgNrZXkYASABKA0SDQoFdmFsdWUY",
            "AiABKA0iLQoOTXVsdGlWYWx1ZVBhaXISCwoDa2V5GAEgASgNEg4KBnZhbHVl",
            "cxgCIAMoDWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::NydusNetwork.API.Protocol.DataReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::NydusNetwork.API.Protocol.Essence), global::NydusNetwork.API.Protocol.Essence.Parser, new[]{ "DataVersion", "DataBuild", "Abilities", "Buffs", "UnitTypes", "Upgrades", "UnitProducers", "UnitRequiredBuildings", "ResearchProducer", "ResearchRequiredBuildings", "ResearchRequiredResearch" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NydusNetwork.API.Protocol.ValuePair), global::NydusNetwork.API.Protocol.ValuePair.Parser, new[]{ "Key", "Value" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::NydusNetwork.API.Protocol.MultiValuePair), global::NydusNetwork.API.Protocol.MultiValuePair.Parser, new[]{ "Key", "Values" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Essence : pb::IMessage<Essence> {
    private static readonly pb::MessageParser<Essence> _parser = new pb::MessageParser<Essence>(() => new Essence());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Essence> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NydusNetwork.API.Protocol.EssenceReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Essence() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Essence(Essence other) : this() {
      dataVersion_ = other.dataVersion_;
      dataBuild_ = other.dataBuild_;
      abilities_ = other.abilities_.Clone();
      buffs_ = other.buffs_.Clone();
      unitTypes_ = other.unitTypes_.Clone();
      upgrades_ = other.upgrades_.Clone();
      unitProducers_ = other.unitProducers_.Clone();
      unitRequiredBuildings_ = other.unitRequiredBuildings_.Clone();
      researchProducer_ = other.researchProducer_.Clone();
      researchRequiredBuildings_ = other.researchRequiredBuildings_.Clone();
      researchRequiredResearch_ = other.researchRequiredResearch_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Essence Clone() {
      return new Essence(this);
    }

    /// <summary>Field number for the "DataVersion" field.</summary>
    public const int DataVersionFieldNumber = 1;
    private string dataVersion_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string DataVersion {
      get { return dataVersion_; }
      set {
        dataVersion_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "DataBuild" field.</summary>
    public const int DataBuildFieldNumber = 2;
    private int dataBuild_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DataBuild {
      get { return dataBuild_; }
      set {
        dataBuild_ = value;
      }
    }

    /// <summary>Field number for the "abilities" field.</summary>
    public const int AbilitiesFieldNumber = 3;
    private static readonly pb::FieldCodec<global::NydusNetwork.API.Protocol.AbilityData> _repeated_abilities_codec
        = pb::FieldCodec.ForMessage(26, global::NydusNetwork.API.Protocol.AbilityData.Parser);
    private readonly pbc::RepeatedField<global::NydusNetwork.API.Protocol.AbilityData> abilities_ = new pbc::RepeatedField<global::NydusNetwork.API.Protocol.AbilityData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::NydusNetwork.API.Protocol.AbilityData> Abilities {
      get { return abilities_; }
    }

    /// <summary>Field number for the "buffs" field.</summary>
    public const int BuffsFieldNumber = 4;
    private static readonly pb::FieldCodec<global::NydusNetwork.API.Protocol.BuffData> _repeated_buffs_codec
        = pb::FieldCodec.ForMessage(34, global::NydusNetwork.API.Protocol.BuffData.Parser);
    private readonly pbc::RepeatedField<global::NydusNetwork.API.Protocol.BuffData> buffs_ = new pbc::RepeatedField<global::NydusNetwork.API.Protocol.BuffData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::NydusNetwork.API.Protocol.BuffData> Buffs {
      get { return buffs_; }
    }

    /// <summary>Field number for the "unitTypes" field.</summary>
    public const int UnitTypesFieldNumber = 5;
    private static readonly pb::FieldCodec<global::NydusNetwork.API.Protocol.UnitTypeData> _repeated_unitTypes_codec
        = pb::FieldCodec.ForMessage(42, global::NydusNetwork.API.Protocol.UnitTypeData.Parser);
    private readonly pbc::RepeatedField<global::NydusNetwork.API.Protocol.UnitTypeData> unitTypes_ = new pbc::RepeatedField<global::NydusNetwork.API.Protocol.UnitTypeData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::NydusNetwork.API.Protocol.UnitTypeData> UnitTypes {
      get { return unitTypes_; }
    }

    /// <summary>Field number for the "upgrades" field.</summary>
    public const int UpgradesFieldNumber = 6;
    private static readonly pb::FieldCodec<global::NydusNetwork.API.Protocol.UpgradeData> _repeated_upgrades_codec
        = pb::FieldCodec.ForMessage(50, global::NydusNetwork.API.Protocol.UpgradeData.Parser);
    private readonly pbc::RepeatedField<global::NydusNetwork.API.Protocol.UpgradeData> upgrades_ = new pbc::RepeatedField<global::NydusNetwork.API.Protocol.UpgradeData>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::NydusNetwork.API.Protocol.UpgradeData> Upgrades {
      get { return upgrades_; }
    }

    /// <summary>Field number for the "unitProducers" field.</summary>
    public const int UnitProducersFieldNumber = 7;
    private static readonly pb::FieldCodec<global::NydusNetwork.API.Protocol.MultiValuePair> _repeated_unitProducers_codec
        = pb::FieldCodec.ForMessage(58, global::NydusNetwork.API.Protocol.MultiValuePair.Parser);
    private readonly pbc::RepeatedField<global::NydusNetwork.API.Protocol.MultiValuePair> unitProducers_ = new pbc::RepeatedField<global::NydusNetwork.API.Protocol.MultiValuePair>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::NydusNetwork.API.Protocol.MultiValuePair> UnitProducers {
      get { return unitProducers_; }
    }

    /// <summary>Field number for the "unitRequiredBuildings" field.</summary>
    public const int UnitRequiredBuildingsFieldNumber = 8;
    private static readonly pb::FieldCodec<global::NydusNetwork.API.Protocol.MultiValuePair> _repeated_unitRequiredBuildings_codec
        = pb::FieldCodec.ForMessage(66, global::NydusNetwork.API.Protocol.MultiValuePair.Parser);
    private readonly pbc::RepeatedField<global::NydusNetwork.API.Protocol.MultiValuePair> unitRequiredBuildings_ = new pbc::RepeatedField<global::NydusNetwork.API.Protocol.MultiValuePair>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::NydusNetwork.API.Protocol.MultiValuePair> UnitRequiredBuildings {
      get { return unitRequiredBuildings_; }
    }

    /// <summary>Field number for the "researchProducer" field.</summary>
    public const int ResearchProducerFieldNumber = 9;
    private static readonly pb::FieldCodec<global::NydusNetwork.API.Protocol.ValuePair> _repeated_researchProducer_codec
        = pb::FieldCodec.ForMessage(74, global::NydusNetwork.API.Protocol.ValuePair.Parser);
    private readonly pbc::RepeatedField<global::NydusNetwork.API.Protocol.ValuePair> researchProducer_ = new pbc::RepeatedField<global::NydusNetwork.API.Protocol.ValuePair>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::NydusNetwork.API.Protocol.ValuePair> ResearchProducer {
      get { return researchProducer_; }
    }

    /// <summary>Field number for the "researchRequiredBuildings" field.</summary>
    public const int ResearchRequiredBuildingsFieldNumber = 10;
    private static readonly pb::FieldCodec<global::NydusNetwork.API.Protocol.ValuePair> _repeated_researchRequiredBuildings_codec
        = pb::FieldCodec.ForMessage(82, global::NydusNetwork.API.Protocol.ValuePair.Parser);
    private readonly pbc::RepeatedField<global::NydusNetwork.API.Protocol.ValuePair> researchRequiredBuildings_ = new pbc::RepeatedField<global::NydusNetwork.API.Protocol.ValuePair>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::NydusNetwork.API.Protocol.ValuePair> ResearchRequiredBuildings {
      get { return researchRequiredBuildings_; }
    }

    /// <summary>Field number for the "researchRequiredResearch" field.</summary>
    public const int ResearchRequiredResearchFieldNumber = 11;
    private static readonly pb::FieldCodec<global::NydusNetwork.API.Protocol.ValuePair> _repeated_researchRequiredResearch_codec
        = pb::FieldCodec.ForMessage(90, global::NydusNetwork.API.Protocol.ValuePair.Parser);
    private readonly pbc::RepeatedField<global::NydusNetwork.API.Protocol.ValuePair> researchRequiredResearch_ = new pbc::RepeatedField<global::NydusNetwork.API.Protocol.ValuePair>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::NydusNetwork.API.Protocol.ValuePair> ResearchRequiredResearch {
      get { return researchRequiredResearch_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Essence);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Essence other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DataVersion != other.DataVersion) return false;
      if (DataBuild != other.DataBuild) return false;
      if(!abilities_.Equals(other.abilities_)) return false;
      if(!buffs_.Equals(other.buffs_)) return false;
      if(!unitTypes_.Equals(other.unitTypes_)) return false;
      if(!upgrades_.Equals(other.upgrades_)) return false;
      if(!unitProducers_.Equals(other.unitProducers_)) return false;
      if(!unitRequiredBuildings_.Equals(other.unitRequiredBuildings_)) return false;
      if(!researchProducer_.Equals(other.researchProducer_)) return false;
      if(!researchRequiredBuildings_.Equals(other.researchRequiredBuildings_)) return false;
      if(!researchRequiredResearch_.Equals(other.researchRequiredResearch_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DataVersion.Length != 0) hash ^= DataVersion.GetHashCode();
      if (DataBuild != 0) hash ^= DataBuild.GetHashCode();
      hash ^= abilities_.GetHashCode();
      hash ^= buffs_.GetHashCode();
      hash ^= unitTypes_.GetHashCode();
      hash ^= upgrades_.GetHashCode();
      hash ^= unitProducers_.GetHashCode();
      hash ^= unitRequiredBuildings_.GetHashCode();
      hash ^= researchProducer_.GetHashCode();
      hash ^= researchRequiredBuildings_.GetHashCode();
      hash ^= researchRequiredResearch_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DataVersion.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(DataVersion);
      }
      if (DataBuild != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(DataBuild);
      }
      abilities_.WriteTo(output, _repeated_abilities_codec);
      buffs_.WriteTo(output, _repeated_buffs_codec);
      unitTypes_.WriteTo(output, _repeated_unitTypes_codec);
      upgrades_.WriteTo(output, _repeated_upgrades_codec);
      unitProducers_.WriteTo(output, _repeated_unitProducers_codec);
      unitRequiredBuildings_.WriteTo(output, _repeated_unitRequiredBuildings_codec);
      researchProducer_.WriteTo(output, _repeated_researchProducer_codec);
      researchRequiredBuildings_.WriteTo(output, _repeated_researchRequiredBuildings_codec);
      researchRequiredResearch_.WriteTo(output, _repeated_researchRequiredResearch_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DataVersion.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(DataVersion);
      }
      if (DataBuild != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DataBuild);
      }
      size += abilities_.CalculateSize(_repeated_abilities_codec);
      size += buffs_.CalculateSize(_repeated_buffs_codec);
      size += unitTypes_.CalculateSize(_repeated_unitTypes_codec);
      size += upgrades_.CalculateSize(_repeated_upgrades_codec);
      size += unitProducers_.CalculateSize(_repeated_unitProducers_codec);
      size += unitRequiredBuildings_.CalculateSize(_repeated_unitRequiredBuildings_codec);
      size += researchProducer_.CalculateSize(_repeated_researchProducer_codec);
      size += researchRequiredBuildings_.CalculateSize(_repeated_researchRequiredBuildings_codec);
      size += researchRequiredResearch_.CalculateSize(_repeated_researchRequiredResearch_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Essence other) {
      if (other == null) {
        return;
      }
      if (other.DataVersion.Length != 0) {
        DataVersion = other.DataVersion;
      }
      if (other.DataBuild != 0) {
        DataBuild = other.DataBuild;
      }
      abilities_.Add(other.abilities_);
      buffs_.Add(other.buffs_);
      unitTypes_.Add(other.unitTypes_);
      upgrades_.Add(other.upgrades_);
      unitProducers_.Add(other.unitProducers_);
      unitRequiredBuildings_.Add(other.unitRequiredBuildings_);
      researchProducer_.Add(other.researchProducer_);
      researchRequiredBuildings_.Add(other.researchRequiredBuildings_);
      researchRequiredResearch_.Add(other.researchRequiredResearch_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            DataVersion = input.ReadString();
            break;
          }
          case 16: {
            DataBuild = input.ReadInt32();
            break;
          }
          case 26: {
            abilities_.AddEntriesFrom(input, _repeated_abilities_codec);
            break;
          }
          case 34: {
            buffs_.AddEntriesFrom(input, _repeated_buffs_codec);
            break;
          }
          case 42: {
            unitTypes_.AddEntriesFrom(input, _repeated_unitTypes_codec);
            break;
          }
          case 50: {
            upgrades_.AddEntriesFrom(input, _repeated_upgrades_codec);
            break;
          }
          case 58: {
            unitProducers_.AddEntriesFrom(input, _repeated_unitProducers_codec);
            break;
          }
          case 66: {
            unitRequiredBuildings_.AddEntriesFrom(input, _repeated_unitRequiredBuildings_codec);
            break;
          }
          case 74: {
            researchProducer_.AddEntriesFrom(input, _repeated_researchProducer_codec);
            break;
          }
          case 82: {
            researchRequiredBuildings_.AddEntriesFrom(input, _repeated_researchRequiredBuildings_codec);
            break;
          }
          case 90: {
            researchRequiredResearch_.AddEntriesFrom(input, _repeated_researchRequiredResearch_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ValuePair : pb::IMessage<ValuePair> {
    private static readonly pb::MessageParser<ValuePair> _parser = new pb::MessageParser<ValuePair>(() => new ValuePair());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ValuePair> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NydusNetwork.API.Protocol.EssenceReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValuePair() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValuePair(ValuePair other) : this() {
      key_ = other.key_;
      value_ = other.value_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValuePair Clone() {
      return new ValuePair(this);
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 1;
    private uint key_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Key {
      get { return key_; }
      set {
        key_ = value;
      }
    }

    /// <summary>Field number for the "value" field.</summary>
    public const int ValueFieldNumber = 2;
    private uint value_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Value {
      get { return value_; }
      set {
        value_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ValuePair);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ValuePair other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Key != other.Key) return false;
      if (Value != other.Value) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Key != 0) hash ^= Key.GetHashCode();
      if (Value != 0) hash ^= Value.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Key != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Key);
      }
      if (Value != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Value);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Key != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Key);
      }
      if (Value != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Value);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ValuePair other) {
      if (other == null) {
        return;
      }
      if (other.Key != 0) {
        Key = other.Key;
      }
      if (other.Value != 0) {
        Value = other.Value;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Key = input.ReadUInt32();
            break;
          }
          case 16: {
            Value = input.ReadUInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class MultiValuePair : pb::IMessage<MultiValuePair> {
    private static readonly pb::MessageParser<MultiValuePair> _parser = new pb::MessageParser<MultiValuePair>(() => new MultiValuePair());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<MultiValuePair> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::NydusNetwork.API.Protocol.EssenceReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MultiValuePair() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MultiValuePair(MultiValuePair other) : this() {
      key_ = other.key_;
      values_ = other.values_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MultiValuePair Clone() {
      return new MultiValuePair(this);
    }

    /// <summary>Field number for the "key" field.</summary>
    public const int KeyFieldNumber = 1;
    private uint key_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public uint Key {
      get { return key_; }
      set {
        key_ = value;
      }
    }

    /// <summary>Field number for the "values" field.</summary>
    public const int ValuesFieldNumber = 2;
    private static readonly pb::FieldCodec<uint> _repeated_values_codec
        = pb::FieldCodec.ForUInt32(18);
    private readonly pbc::RepeatedField<uint> values_ = new pbc::RepeatedField<uint>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<uint> Values {
      get { return values_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as MultiValuePair);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(MultiValuePair other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Key != other.Key) return false;
      if(!values_.Equals(other.values_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Key != 0) hash ^= Key.GetHashCode();
      hash ^= values_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Key != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Key);
      }
      values_.WriteTo(output, _repeated_values_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Key != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Key);
      }
      size += values_.CalculateSize(_repeated_values_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(MultiValuePair other) {
      if (other == null) {
        return;
      }
      if (other.Key != 0) {
        Key = other.Key;
      }
      values_.Add(other.values_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Key = input.ReadUInt32();
            break;
          }
          case 18:
          case 16: {
            values_.AddEntriesFrom(input, _repeated_values_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
